device_id: cpu
cpu_num: 16
conf: 0.4
iou: 0.65
server_port: 8081
url: /ailab/multimedia/nap/detect
model_path: /home/models/nap_detect_v1.0_41c18d829669e6fd8216705e3af3f5e7.pt


# decode type can be "cpu": : 0 or "gpu": : 1
decode_type :  0
# 0:GRAY,1:BGR
cpu_decode_output_img_type :  1
gpu_decode_thread_num :  1
gpu_decode_ouput_img_type :  1
max_size :  1920 * 1080 * 3


post_url: 
send_info_time_interval: 

